version: '3.8'

services:
  rag_pg_vector:
    image: ankane/pgvector
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: